import paper from "../assets/quetionpaper/paper1.pdf"
const materialdata = [
  {
    id: 1,
    title: "Data Structures Question Paper",
    description: "University End Semester Examination",
    type: "PYQ",
    department: "CSE",
    semester: "Sem 3",
    subject: "Data Structures",
    year: "2022",
    examType: "End Sem",
    downloads: 320,
    size: "1.2 MB",
    fileUrl: paper,
  },
  {
    id: 2,
    title: "DBMS Question Paper",
    description: "Mid Semester Examination",
    type: "PYQ",
    department: "CSE",
    semester: "Sem 4",
    subject: "DBMS",
    year: "2023",
    examType: "Mid Sem",
    downloads: 210,
    size: "980 KB",
    fileUrl: "/files/dbms-2023.pdf",
  },
  {
    id: 3,
    title: "Operating Systems Question Paper",
    description: "University End Semester Examination",
    type: "PYQ",
    department: "CSE",
    semester: "Sem 5",
    subject: "Operating Systems",
    year: "2024",
    examType: "End Sem",
    downloads: 450,
    size: "1.5 MB",
    fileUrl: "/files/os-2024.pdf",
  },
  {
    id: 4,
    title: "Computer Networks Question Paper",
    description: "University End Semester Examination",
    type: "PYQ",
    department: "CSE",
    semester: "Sem 5",
    subject: "Computer Networks",
    year: "2025",
    examType: "End Sem",
    downloads: 380,
    size: "1.1 MB",
    fileUrl: "/files/cn-2025.pdf",
  },
  {
    id: 5,
    title: "Digital Electronics Question Paper",
    description: "Mid Semester Examination",
    type: "PYQ",
    department: "ECE",
    semester: "Sem 3",
    subject: "Digital Electronics",
    year: "2022",
    examType: "Mid Sem",
    downloads: 260,
    size: "900 KB",
    fileUrl: "/files/de-2022.pdf",
  },
    {
    id: 5,
    title: "Digital Electronics Question Paper",
    description: "Mid Semester Examination",
    type: "PYQ",
    department: "ECE",
    semester: "Sem 3",
    subject: "Digital Electronics",
    year: "2022",
    examType: "Mid Sem",
    downloads: 260,
    size: "900 KB",
    fileUrl: "/files/de-2022.pdf",
  },

];

export default materialdata;
